AWSTemplateFormatVersion: '2010-09-09'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      Tags:
        - Key: bridgecrew
          Value: drift-demo
        - Key: Class
          Value: Sovereign
        -
          Key: Tag
          Value: Fine
      BucketName: s3-bucket-bcdemo-drift-7171a6b0
        - "-"
        - - "s3-bucket-bcdemo-drift"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId" 
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      InventoryConfigurations:
        - Destination:
            BucketAccountId: 188619942792
          Prefix: inventory-report/daily
          Format: Parquet
          BucketArn: arn:aws:s3:::pcdsprodus-s3-inventory-us-east-1
        Id: pcdsprodus-pcds-sizing-estimate


